### ISSUE TITLE
Fix lancer logo in footer

### ISSUE THREAD

**Issue by patnebe** [hngi/Lancer#269]
![image](https://user-images.githubusercontent.com/15070069/66708855-4fe33380-ed4f-11e9-874c-7af474be53c2.png)

Please inform whoever hosted that footer image to look into it. It's not loading properly and it's also affecting the payments page because I'm using that same footer. Thanks

**Comment by phiiileo** [comment]
It's something you can fix, so please do

**Comment by Dev-Nebe** [comment]
Lol so this is how you would have been waiting for me to do it? issokay. I'm on it now sha, I just got light since yesterday.

**Comment by Dev-Nebe** [comment]
Hi, I fixed the logo issue on the Lancer footer but I can't find the correct index.html code to make a PR to. Which one is the correct homepage? All the ones on Github seem to be broken.

I've made a PR to the pricing.html page cos that page also uses the same footer. So can grab the footer from the pricing.html and reuse it in the index.html file.

**Comment by Dev-Nebe** [comment]
Test link: https://dev-nebe.github.io/Lancer/
